language: java

cache:
  directories:
   - "$HOME/.cache"
   - "$HOME/.m2"
   
jdk:
  - openjdk8

build:
  - mvn package
  - mvn javadoc:jar
  - mvn source:jar

deploy:
  provider: releases
  access_token: $GH_TOKEN
  file_glob: true
  file: 
    - target/netbeans-jemmy-*.jar
  skip_cleanup: true
  on:
    branch: add-travis-ci


