language: java

cache:
  directories:
   - "$HOME/.cache"
   - "$HOME/.m2"
   
jdk:
  - openjdk8

jobs:
  include:
    - script: mvn test -B
    - stage: Generate main artifact
      script: mvn package
    - stage: Generate Javadoc artifact
      script: mvn javadoc:jar
    - stage: Generate Source code artifact
      script: mvn source:jar
