language: java

cache:
  directories:
   - "$HOME/.cache"
   - "$HOME/.m2"
   
jdk:
  - openjdk8

build:
  - mvn package
  - mvn javadoc:jar
  - mvn source:jar

deploy:
  provider: releases
  api_key:
    secure: asdlkfjasdflkasdfkl
  file: 
    - target/netbeans-jemmy-*.jar
  skip_cleanup: true
  on:
    branch: add-travis-ci


